name: markdown-to-mkdown-converter
description: convert markdown to slack mkdown
author: GitHub Actions

# Define your inputs here.
inputs:
  text:
    description: markdown text to convert
    required: true

# Define your outputs here.
outputs:
  text:
    description: mkdown

runs:
  using: docker
  image: docker://ghcr.io/letsbuilders/markdown-to-mrkdwn-action:sha-62af71b38d4e80f0aa7f6e92d6c3624ce61b9808
#  image: docker://ghcr.io/letsbuilders/markdown-to-mrkdwn-action@latest
  env:
    INPUT_TEXT: ${{ inputs.text }}