name: markdown-to-mkdown-converter
description: convert markdown to slack mkdown
author: GitHub Actions

# Define your inputs here.
inputs:
  text:
    description: markdown text to convert
    required: true

# Define your outputs here.
outputs:
  text:
    description: mkdown

runs:
  using: docker
  # for development uncomment the Dockerfile line and comment out the latest image one
#  image: Dockerfile
  image: docker://ghcr.io/letsbuilders/markdown-to-mrkdwn-action:latest
  env:
    INPUT_TEXT: ${{ inputs.text }}